#!/usr/bin/env python3
"""
Plot training curves from training logs and trainer state.

Supports:
1. `trainer_log.jsonl` generated by the Hugging Face trainer
2. `trainer_state.json` generated by the Hugging Face trainer
3. plain-text terminal logs that contain JSON metric lines

If `trainer_log.jsonl` does not contain eval rows but a sibling `trainer_state.json`
exists in the same run directory, the script will automatically merge the missing
metrics from `trainer_state.json`.

Example:
    python3 training/plot_training_log.py \
        --log-file training/outputs/run_xxx/trainer_log.jsonl

    python3 training/plot_training_log.py \
        --log-file training/outputs/run_xxx/trainer_state.json

    python3 training/plot_training_log.py \
        --log-file training_logs/model_b_full_tulu3.log \
        --output training_logs/model_b_full_tulu3_curve.png
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


def try_parse_json_line(line: str) -> dict[str, Any] | None:
    line = line.strip()
    if not line or not line.startswith("{") or not line.endswith("}"):
        return None
    try:
        value = json.loads(line)
    except json.JSONDecodeError:
        return None
    return value if isinstance(value, dict) else None


def load_metric_rows_from_json_lines(log_file: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with log_file.open("r", encoding="utf-8") as f:
        for line in f:
            parsed = try_parse_json_line(line)
            if parsed is not None:
                rows.append(parsed)
    return rows


def load_metric_rows_from_trainer_state(state_file: Path) -> list[dict[str, Any]]:
    try:
        payload = json.loads(state_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid trainer_state.json: {state_file}") from exc

    log_history = payload.get("log_history", [])
    if not isinstance(log_history, list):
        raise ValueError(f"`log_history` is missing or invalid in: {state_file}")

    return [row for row in log_history if isinstance(row, dict)]


def pick_step(row: dict[str, Any]) -> int | float | None:
    for key in ("current_steps", "step", "global_step"):
        if key in row:
            return row[key]
    return None


def row_signature(row: dict[str, Any]) -> str:
    return json.dumps(row, ensure_ascii=False, sort_keys=True, default=str)


def merge_metric_rows(
    primary_rows: list[dict[str, Any]],
    secondary_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    combined = list(primary_rows)
    seen = {row_signature(row) for row in primary_rows}

    for row in secondary_rows:
        signature = row_signature(row)
        if signature not in seen:
            combined.append(row)
            seen.add(signature)

    indexed_rows = list(enumerate(combined))

    def sort_key(item: tuple[int, dict[str, Any]]) -> tuple[int, float, int]:
        idx, row = item
        step = pick_step(row)
        try:
            return (0, float(step), idx) if step is not None else (1, float("inf"), idx)
        except (TypeError, ValueError):
            return (1, float("inf"), idx)

    indexed_rows.sort(key=sort_key)
    return [row for _, row in indexed_rows]


def load_metric_rows(log_file: Path) -> list[dict[str, Any]]:
    if log_file.name == "trainer_state.json":
        return load_metric_rows_from_trainer_state(log_file)

    rows = load_metric_rows_from_json_lines(log_file)

    trainer_state_path = log_file.parent / "trainer_state.json"
    if trainer_state_path.exists():
        rows = merge_metric_rows(rows, load_metric_rows_from_trainer_state(trainer_state_path))

    return rows


def load_training_command(run_dir: Path) -> list[str]:
    cmd_path = run_dir / "training_command.txt"
    if not cmd_path.exists():
        return []
    return shlex.split(cmd_path.read_text(encoding="utf-8").strip())


def extract_series(rows: list[dict[str, Any]], key: str) -> tuple[list[float], list[float]]:
    xs: list[float] = []
    ys: list[float] = []
    for row in rows:
        if key not in row:
            continue
        step = pick_step(row)
        if step is None:
            continue
        try:
            xs.append(float(step))
            ys.append(float(row[key]))
        except (TypeError, ValueError):
            continue
    return xs, ys


def collect_eval_loss_series(rows: list[dict[str, Any]]) -> dict[str, tuple[list[float], list[float]]]:
    eval_keys: set[str] = set()
    for row in rows:
        for key in row:
            if key == "eval_loss" or (key.startswith("eval_") and key.endswith("_loss")):
                eval_keys.add(key)

    ordered_keys = sorted(
        eval_keys,
        key=lambda key: (0 if key == "eval_loss" else 1, key),
    )
    return {key: extract_series(rows, key) for key in ordered_keys}


def parse_dataset_dir_from_command(run_dir: Path) -> Path | None:
    tokens = load_training_command(run_dir)
    for idx, token in enumerate(tokens):
        if token == "--dataset_dir" and idx + 1 < len(tokens):
            return Path(tokens[idx + 1]).expanduser()
    return None


def strip_task_eval_key(key: str) -> str | None:
    match = re.fullmatch(r"eval_(.+)_loss", key)
    if not match:
        return None
    dataset_name = match.group(1)
    if not dataset_name.startswith("evolvingworld_") or not dataset_name.endswith("_eval"):
        return None
    if dataset_name.count("_") < 4:
        return None
    return dataset_name


def load_eval_dataset_weights(log_file: Path, eval_keys: list[str]) -> dict[str, int]:
    run_dir = log_file.parent
    dataset_dir = parse_dataset_dir_from_command(run_dir)
    if dataset_dir is None:
        return {}

    dataset_info_path = dataset_dir / "dataset_info.json"
    if not dataset_info_path.exists():
        return {}

    info = json.loads(dataset_info_path.read_text(encoding="utf-8"))
    weights: dict[str, int] = {}
    for key in eval_keys:
        dataset_name = strip_task_eval_key(key)
        if not dataset_name or dataset_name not in info:
            continue
        file_name = info[dataset_name]["file_name"]
        data_path = dataset_dir / file_name
        if not data_path.exists():
            continue
        with data_path.open("r", encoding="utf-8") as f:
            try:
                weights[key] = len(json.load(f))
            except json.JSONDecodeError:
                # JSONL format: count non-empty lines
                f.seek(0)
                weights[key] = sum(1 for line in f if line.strip())
    return weights


def build_overall_eval_series(
    rows: list[dict[str, Any]],
    log_file: Path,
) -> tuple[list[float], list[float]] | None:
    eval_series = collect_eval_loss_series(rows)
    if "eval_loss" in eval_series:
        return None

    task_keys = [key for key in eval_series if strip_task_eval_key(key)]
    if len(task_keys) < 2:
        return None

    weights = load_eval_dataset_weights(log_file, task_keys)
    if len(weights) != len(task_keys):
        return None

    keyed_rows: dict[float, dict[str, float]] = {}
    for key in task_keys:
        xs, ys = eval_series[key]
        for x, y in zip(xs, ys):
            keyed_rows.setdefault(x, {})[key] = y

    overall_x: list[float] = []
    overall_y: list[float] = []
    total_weight = sum(weights.values())
    for step in sorted(keyed_rows):
        row_values = keyed_rows[step]
        if any(key not in row_values for key in task_keys):
            continue
        weighted_loss = sum(row_values[key] * weights[key] for key in task_keys) / total_weight
        overall_x.append(step)
        overall_y.append(weighted_loss)
    return (overall_x, overall_y) if overall_x else None


def plot_rows(rows: list[dict[str, Any]], output_path: Path, title: str, log_file: Path) -> None:
    train_x, train_loss = extract_series(rows, "loss")
    eval_series = collect_eval_loss_series(rows)
    lr_x, lrs = extract_series(rows, "lr")
    overall_eval = build_overall_eval_series(rows, log_file)

    if not train_loss and not eval_series and not lrs:
        raise ValueError("No plottable metric rows found in the log file.")

    # Filter out empty eval series
    nonempty_eval = {k: v for k, v in eval_series.items() if v[1]}
    n_eval = len(nonempty_eval)

    # Layout: train_loss + one subplot per eval series + overall_eval (if present) + lr
    n_rows = 1 + max(n_eval, 1) + (1 if overall_eval else 0) + 1
    fig, axes = plt.subplots(n_rows, 1, figsize=(12, 4 * n_rows), sharex=True)
    fig.suptitle(title)

    ax_idx = 0

    # --- Train Loss ---
    if train_loss:
        axes[ax_idx].plot(train_x, train_loss, color="#2563eb", linewidth=1.5, label="train_loss")
        axes[ax_idx].legend()
    axes[ax_idx].set_ylabel("Train Loss")
    axes[ax_idx].grid(True, alpha=0.3)
    ax_idx += 1

    # --- Individual Eval Loss subplots ---
    colors = [
        "#dc2626",
        "#ea580c",
        "#d97706",
        "#65a30d",
        "#0891b2",
        "#2563eb",
        "#7c3aed",
        "#db2777",
    ]
    if nonempty_eval:
        for idx, (key, (eval_x, eval_loss)) in enumerate(nonempty_eval.items()):
            axes[ax_idx].plot(
                eval_x,
                eval_loss,
                color=colors[idx % len(colors)],
                linewidth=1.5,
                label=key,
            )
            axes[ax_idx].legend(fontsize=8)
            axes[ax_idx].set_ylabel("Eval Loss")
            axes[ax_idx].grid(True, alpha=0.3)
            ax_idx += 1
    else:
        # Placeholder empty eval subplot
        axes[ax_idx].set_ylabel("Eval Loss")
        axes[ax_idx].grid(True, alpha=0.3)
        ax_idx += 1

    # --- Overall Eval Loss ---
    if overall_eval:
        axes[ax_idx].plot(
            overall_eval[0],
            overall_eval[1],
            color="#111827",
            linewidth=2.0,
            linestyle="--",
            label="overall_eval_loss",
        )
        axes[ax_idx].legend(fontsize=8)
        axes[ax_idx].set_ylabel("Overall Eval Loss")
        axes[ax_idx].grid(True, alpha=0.3)
        ax_idx += 1

    # --- Learning Rate ---
    if lrs:
        axes[ax_idx].plot(lr_x, lrs, color="#16a34a", linewidth=1.5, label="learning_rate")
        axes[ax_idx].legend()
    axes[ax_idx].set_ylabel("LR")
    axes[ax_idx].set_xlabel("Step")
    axes[ax_idx].grid(True, alpha=0.3)

    for axis in axes:
        axis.xaxis.set_major_locator(MaxNLocator(nbins=12, integer=True, min_n_ticks=8))

    plt.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot training curves from trainer logs or trainer state.")
    parser.add_argument("--log-file", required=True, help="Path to trainer_log.jsonl, trainer_state.json, or a terminal log")
    parser.add_argument(
        "--output",
        default=None,
        help="Output PNG path. Defaults to <log-file stem>_curve.png",
    )
    parser.add_argument(
        "--title",
        default=None,
        help="Optional figure title. Defaults to the log filename.",
    )
    args = parser.parse_args()

    log_file = Path(args.log_file).expanduser().resolve()
    if not log_file.exists():
        raise FileNotFoundError(f"Log file not found: {log_file}")

    output_path = (
        Path(args.output).expanduser().resolve()
        if args.output
        else log_file.with_name(f"{log_file.stem}_curve.png")
    )
    title = args.title or log_file.name

    rows = load_metric_rows(log_file)
    if not rows:
        raise ValueError(
            "No plottable metric rows found. Pass a `trainer_log.jsonl`, `trainer_state.json`, "
            "or a terminal log that contains JSON metric lines."
        )
    plot_rows(rows, output_path, title, log_file)
    print(f"Saved curve plot to: {output_path}")


if __name__ == "__main__":
    main()
